name: RedstoneAPI
main: net.redstonecraft.redstoneapi.spigot.RedstoneAPISpigot
version: 1.1
author: Redstonecrafter0
permissions:
  redstoneapi.admin.notifyupdate:
    default: op
    description: 'Get notified when a new version of the RedstoneAPI is available.'
