name: RedstoneAPI
main: net.redstonecraft.redstoneapi.spigot.plugin.RedstoneAPISpigot
version: 1.4
author: Redstonecrafter0
softdepend:
  - ProtocolLib
permissions:
  redstoneapi.admin.notifyupdate:
    default: op
    description: 'Get notified when a new version of the RedstoneAPI is available.'
